//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "group")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub name: String,
  #[sea_orm(has_many)]
  pub group_permissions: HasMany<super::group_permission::Entity>,
  #[sea_orm(has_many, via = "group_user")]
  pub users: HasMany<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
