//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod group;
pub mod group_permission;
pub mod group_user;
pub mod invalid_jwt;
pub mod key;
pub mod settings;
pub mod setup;
pub mod user;
