//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::group::Entity as Group;
pub use super::group_permission::Entity as GroupPermission;
pub use super::group_user::Entity as GroupUser;
pub use super::invalid_jwt::Entity as InvalidJwt;
pub use super::key::Entity as Key;
pub use super::settings::Entity as Settings;
pub use super::setup::Entity as Setup;
pub use super::user::Entity as User;
