//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "setup")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub admin_group_created: Option<Uuid>,
  pub completed: bool,
}

impl ActiveModelBehavior for ActiveModel {}
