// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultBodyType,
  http,
  type HttpHandler,
  HttpResponse,
  type HttpResponseResolver,
  type RequestHandlerOptions as RequestHandlerOptions2
} from 'msw';

import type {
  AuthConfigResponses,
  AuthenticateData,
  AvatarByIdResponses,
  ChangeUserEmailData,
  ChangeUserEmailResponses,
  ClientOptions,
  CompleteSetupData,
  ConfirmEmailChangeData,
  ConfirmEmailChangeResponses,
  ConvertOidcUserData,
  ConvertOidcUserResponses,
  CreateGroupData,
  CreateGroupResponses,
  CreateUserData,
  CreateUserResponses,
  DeleteGroupData,
  DeleteGroupResponses,
  DeleteUserData,
  DeleteUserResponses,
  EditGroupData,
  EditGroupResponses,
  EditUserData,
  EditUserResponses,
  GetGeneralSettingsResponses,
  GetMailSettingsResponses,
  GetOidcSettingsResponses,
  GetUserSettingsResponses,
  GroupInfoResponses,
  InfoResponses,
  InitOidcData,
  InitOidcResponses,
  IsSetupResponses,
  KeyResponses,
  ListGroupsResponses,
  ListGroupsSimpleResponses,
  ListUsersResponses,
  ListUsersSimpleResponses,
  MailActiveResponses,
  ResetPasswordData,
  ResetPasswordResponses,
  ResetUserAvatarData,
  ResetUserAvatarResponses,
  ResetUserPasswordData,
  ResetUserPasswordResponses,
  SaveMailSettingsData,
  SaveMailSettingsResponses,
  SaveUserSettingsData,
  SaveUserSettingsResponses,
  SendResetLinkData,
  SendResetLinkResponses,
  StartEmailChangeData,
  StartEmailChangeResponses,
  TestMailResponses,
  TestResponses,
  UpdateAccountData,
  UpdateAccountResponses,
  UpdateAvatarData,
  UpdateAvatarResponses,
  UpdatePasswordData,
  UpdatePasswordResponses,
  UserInfoResponses
} from './types.gen';

export type RequestHandlerOptions = RequestHandlerOptions2 & {
  baseUrl?: ClientOptions['baseUrl'];
  responseFallback?: 'error' | 'passthrough';
};

export type HandleIsSetupResponse = {
  body: IsSetupResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/setup` operation.
 */
export function handleIsSetup(
  response?: HandleIsSetupResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/api/setup`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleCompleteSetupResponse = {
  body: DefaultBodyType;
  status?: number;
};

/**
 * Handler for the `POST /api/setup` operation.
 */
export function handleCompleteSetup(
  response?:
    | HandleCompleteSetupResponse
    | HttpResponseResolver<never, CompleteSetupData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, CompleteSetupData['body']>(
    `${options?.baseUrl ?? '*'}/api/setup`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleGetOidcSettingsResponse = {
  body: GetOidcSettingsResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/setup/oidc` operation.
 */
export function handleGetOidcSettings(
  response?: HandleGetOidcSettingsResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/api/setup/oidc`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleInitOidcResponse = {
  body: InitOidcResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /api/setup/oidc` operation.
 */
export function handleInitOidc(
  response?:
    | HandleInitOidcResponse
    | HttpResponseResolver<never, InitOidcData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, InitOidcData['body']>(
    `${options?.baseUrl ?? '*'}/api/setup/oidc`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleKeyResponse = {
  body: KeyResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/auth/password` operation.
 */
export function handleKey(
  response?: HandleKeyResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/api/auth/password`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleAuthenticateResponse = {
  body: DefaultBodyType;
  status?: number;
};

/**
 * Handler for the `POST /api/auth/password` operation.
 */
export function handleAuthenticate(
  response?:
    | HandleAuthenticateResponse
    | HttpResponseResolver<never, AuthenticateData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, AuthenticateData['body']>(
    `${options?.baseUrl ?? '*'}/api/auth/password`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleLogoutResponse = {
  body: DefaultBodyType;
  status?: number;
};

/**
 * Handler for the `POST /api/auth/logout` operation.
 */
export function handleLogout(
  response?: HandleLogoutResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, never>(
    `${options?.baseUrl ?? '*'}/api/auth/logout`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleTestTokenResponse = {
  body: DefaultBodyType;
  status?: number;
};

/**
 * Handler for the `GET /api/auth/test_token` operation.
 */
export function handleTestToken(
  response?: HandleTestTokenResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/api/auth/test_token`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleAuthConfigResponse = {
  body: AuthConfigResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/auth/config` operation.
 */
export function handleAuthConfig(
  response?: HandleAuthConfigResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/api/auth/config`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleUpdatePasswordResponse = {
  body: UpdatePasswordResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /api/user/account/password` operation.
 */
export function handleUpdatePassword(
  response?:
    | HandleUpdatePasswordResponse
    | HttpResponseResolver<never, UpdatePasswordData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, UpdatePasswordData['body']>(
    `${options?.baseUrl ?? '*'}/api/user/account/password`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleStartEmailChangeResponse = {
  body: StartEmailChangeResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /api/user/account/email_change_start` operation.
 */
export function handleStartEmailChange(
  response?:
    | HandleStartEmailChangeResponse
    | HttpResponseResolver<never, StartEmailChangeData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, StartEmailChangeData['body']>(
    `${options?.baseUrl ?? '*'}/api/user/account/email_change_start`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleUpdateAccountResponse = {
  body: UpdateAccountResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /api/user/account/update` operation.
 */
export function handleUpdateAccount(
  response?:
    | HandleUpdateAccountResponse
    | HttpResponseResolver<never, UpdateAccountData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, UpdateAccountData['body']>(
    `${options?.baseUrl ?? '*'}/api/user/account/update`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleConfirmEmailChangeResponse = {
  body: ConfirmEmailChangeResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /api/user/account/email_change_confirm` operation.
 */
export function handleConfirmEmailChange(
  response?:
    | HandleConfirmEmailChangeResponse
    | HttpResponseResolver<never, ConfirmEmailChangeData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, ConfirmEmailChangeData['body']>(
    `${options?.baseUrl ?? '*'}/api/user/account/email_change_confirm`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleUpdateAvatarResponse = {
  body: UpdateAvatarResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /api/user/account/avatar` operation.
 */
export function handleUpdateAvatar(
  response?:
    | HandleUpdateAvatarResponse
    | HttpResponseResolver<never, UpdateAvatarData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, UpdateAvatarData['body']>(
    `${options?.baseUrl ?? '*'}/api/user/account/avatar`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleInfoResponse = {
  body: InfoResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/user/info` operation.
 */
export function handleInfo(
  response?: HandleInfoResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/api/user/info`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleAvatarByIdResponse = {
  body: AvatarByIdResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/user/info/avatar/{uuid}` operation.
 */
export function handleAvatarById(
  response?:
    | HandleAvatarByIdResponse
    | HttpResponseResolver<
        {
          uuid: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<
    {
      uuid: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/api/user/info/avatar/:uuid`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleResetUserAvatarResponse = {
  body: ResetUserAvatarResponses[200];
  status?: 200;
};

/**
 * Handler for the `DELETE /api/user/management/avatar` operation.
 */
export function handleResetUserAvatar(
  response?:
    | HandleResetUserAvatarResponse
    | HttpResponseResolver<never, ResetUserAvatarData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.delete<never, ResetUserAvatarData['body']>(
    `${options?.baseUrl ?? '*'}/api/user/management/avatar`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleDeleteUserResponse = {
  body: DeleteUserResponses[200];
  status?: 200;
};

/**
 * Handler for the `DELETE /api/user/management` operation.
 */
export function handleDeleteUser(
  response?:
    | HandleDeleteUserResponse
    | HttpResponseResolver<never, DeleteUserData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.delete<never, DeleteUserData['body']>(
    `${options?.baseUrl ?? '*'}/api/user/management`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleListUsersResponse = {
  body: ListUsersResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/user/management` operation.
 */
export function handleListUsers(
  response?: HandleListUsersResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/api/user/management`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleCreateUserResponse = {
  body: CreateUserResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /api/user/management` operation.
 */
export function handleCreateUser(
  response?:
    | HandleCreateUserResponse
    | HttpResponseResolver<never, CreateUserData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, CreateUserData['body']>(
    `${options?.baseUrl ?? '*'}/api/user/management`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleEditUserResponse = {
  body: EditUserResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /api/user/management` operation.
 */
export function handleEditUser(
  response?:
    | HandleEditUserResponse
    | HttpResponseResolver<never, EditUserData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.put<never, EditUserData['body']>(
    `${options?.baseUrl ?? '*'}/api/user/management`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleUserInfoResponse = {
  body: UserInfoResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/user/management/{uuid}` operation.
 */
export function handleUserInfo(
  response?:
    | HandleUserInfoResponse
    | HttpResponseResolver<
        {
          uuid: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<
    {
      uuid: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/api/user/management/:uuid`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleMailActiveResponse = {
  body: MailActiveResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/user/management/mail` operation.
 */
export function handleMailActive(
  response?: HandleMailActiveResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/api/user/management/mail`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleListGroupsSimpleResponse = {
  body: ListGroupsSimpleResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/user/management/groups` operation.
 */
export function handleListGroupsSimple(
  response?:
    | HandleListGroupsSimpleResponse
    | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/api/user/management/groups`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleResetUserPasswordResponse = {
  body: ResetUserPasswordResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /api/user/management/password` operation.
 */
export function handleResetUserPassword(
  response?:
    | HandleResetUserPasswordResponse
    | HttpResponseResolver<never, ResetUserPasswordData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.put<never, ResetUserPasswordData['body']>(
    `${options?.baseUrl ?? '*'}/api/user/management/password`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleChangeUserEmailResponse = {
  body: ChangeUserEmailResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /api/user/management/email` operation.
 */
export function handleChangeUserEmail(
  response?:
    | HandleChangeUserEmailResponse
    | HttpResponseResolver<never, ChangeUserEmailData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, ChangeUserEmailData['body']>(
    `${options?.baseUrl ?? '*'}/api/user/management/email`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleConvertOidcUserResponse = {
  body: ConvertOidcUserResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /api/user/management/convert-oidc` operation.
 */
export function handleConvertOidcUser(
  response?:
    | HandleConvertOidcUserResponse
    | HttpResponseResolver<never, ConvertOidcUserData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.put<never, ConvertOidcUserData['body']>(
    `${options?.baseUrl ?? '*'}/api/user/management/convert-oidc`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleGetGeneralSettingsResponse = {
  body: GetGeneralSettingsResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/settings/general` operation.
 */
export function handleGetGeneralSettings(
  response?:
    | HandleGetGeneralSettingsResponse
    | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/api/settings/general`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleGetUserSettingsResponse = {
  body: GetUserSettingsResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/settings/user` operation.
 */
export function handleGetUserSettings(
  response?: HandleGetUserSettingsResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/api/settings/user`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleSaveUserSettingsResponse = {
  body: SaveUserSettingsResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /api/settings/user` operation.
 */
export function handleSaveUserSettings(
  response?:
    | HandleSaveUserSettingsResponse
    | HttpResponseResolver<never, SaveUserSettingsData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, SaveUserSettingsData['body']>(
    `${options?.baseUrl ?? '*'}/api/settings/user`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleGetMailSettingsResponse = {
  body: GetMailSettingsResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/settings/mail` operation.
 */
export function handleGetMailSettings(
  response?: HandleGetMailSettingsResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/api/settings/mail`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleSaveMailSettingsResponse = {
  body: SaveMailSettingsResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /api/settings/mail` operation.
 */
export function handleSaveMailSettings(
  response?:
    | HandleSaveMailSettingsResponse
    | HttpResponseResolver<never, SaveMailSettingsData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, SaveMailSettingsData['body']>(
    `${options?.baseUrl ?? '*'}/api/settings/mail`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleSendResetLinkResponse = {
  body: SendResetLinkResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /api/mail/reset/send` operation.
 */
export function handleSendResetLink(
  response?:
    | HandleSendResetLinkResponse
    | HttpResponseResolver<never, SendResetLinkData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, SendResetLinkData['body']>(
    `${options?.baseUrl ?? '*'}/api/mail/reset/send`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleResetPasswordResponse = {
  body: ResetPasswordResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /api/mail/reset/confirm` operation.
 */
export function handleResetPassword(
  response?:
    | HandleResetPasswordResponse
    | HttpResponseResolver<never, ResetPasswordData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, ResetPasswordData['body']>(
    `${options?.baseUrl ?? '*'}/api/mail/reset/confirm`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleTestMailResponse = {
  body: TestMailResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /api/mail/test` operation.
 */
export function handleTestMail(
  response?: HandleTestMailResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, never>(
    `${options?.baseUrl ?? '*'}/api/mail/test`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleDeleteGroupResponse = {
  body: DeleteGroupResponses[200];
  status?: 200;
};

/**
 * Handler for the `DELETE /api/group` operation.
 */
export function handleDeleteGroup(
  response?:
    | HandleDeleteGroupResponse
    | HttpResponseResolver<never, DeleteGroupData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.delete<never, DeleteGroupData['body']>(
    `${options?.baseUrl ?? '*'}/api/group`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleListGroupsResponse = {
  body: ListGroupsResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/group` operation.
 */
export function handleListGroups(
  response?: HandleListGroupsResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/api/group`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleCreateGroupResponse = {
  body: CreateGroupResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /api/group` operation.
 */
export function handleCreateGroup(
  response?:
    | HandleCreateGroupResponse
    | HttpResponseResolver<never, CreateGroupData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, CreateGroupData['body']>(
    `${options?.baseUrl ?? '*'}/api/group`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleEditGroupResponse = {
  body: EditGroupResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /api/group` operation.
 */
export function handleEditGroup(
  response?:
    | HandleEditGroupResponse
    | HttpResponseResolver<never, EditGroupData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.put<never, EditGroupData['body']>(
    `${options?.baseUrl ?? '*'}/api/group`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleGroupInfoResponse = {
  body: GroupInfoResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/group/{uuid}` operation.
 */
export function handleGroupInfo(
  response?:
    | HandleGroupInfoResponse
    | HttpResponseResolver<
        {
          uuid: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<
    {
      uuid: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/api/group/:uuid`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleListUsersSimpleResponse = {
  body: ListUsersSimpleResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/group/users` operation.
 */
export function handleListUsersSimple(
  response?: HandleListUsersSimpleResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/api/group/users`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type HandleTestResponse = {
  body: TestResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/dummy/test` operation.
 */
export function handleTest(
  response?: HandleTestResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/api/dummy/test`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return new HttpResponse(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented'
      });
    },
    options
  );
}

export type MswHandlerFactories = {
  /**
   * Handler for the `GET /api/setup` operation.
   */
  isSetup: typeof handleIsSetup;
  /**
   * Handler for the `POST /api/setup` operation.
   */
  completeSetup: typeof handleCompleteSetup;
  /**
   * Handler for the `GET /api/setup/oidc` operation.
   */
  getOidcSettings: typeof handleGetOidcSettings;
  /**
   * Handler for the `POST /api/setup/oidc` operation.
   */
  initOidc: typeof handleInitOidc;
  /**
   * Handler for the `GET /api/auth/password` operation.
   */
  key: typeof handleKey;
  /**
   * Handler for the `POST /api/auth/password` operation.
   */
  authenticate: typeof handleAuthenticate;
  /**
   * Handler for the `POST /api/auth/logout` operation.
   */
  logout: typeof handleLogout;
  /**
   * Handler for the `GET /api/auth/test_token` operation.
   */
  testToken: typeof handleTestToken;
  /**
   * Handler for the `GET /api/auth/config` operation.
   */
  authConfig: typeof handleAuthConfig;
  /**
   * Handler for the `POST /api/user/account/password` operation.
   */
  updatePassword: typeof handleUpdatePassword;
  /**
   * Handler for the `POST /api/user/account/email_change_start` operation.
   */
  startEmailChange: typeof handleStartEmailChange;
  /**
   * Handler for the `POST /api/user/account/update` operation.
   */
  updateAccount: typeof handleUpdateAccount;
  /**
   * Handler for the `POST /api/user/account/email_change_confirm` operation.
   */
  confirmEmailChange: typeof handleConfirmEmailChange;
  /**
   * Handler for the `POST /api/user/account/avatar` operation.
   */
  updateAvatar: typeof handleUpdateAvatar;
  /**
   * Handler for the `GET /api/user/info` operation.
   */
  info: typeof handleInfo;
  /**
   * Handler for the `GET /api/user/info/avatar/{uuid}` operation.
   */
  avatarById: typeof handleAvatarById;
  /**
   * Handler for the `DELETE /api/user/management/avatar` operation.
   */
  resetUserAvatar: typeof handleResetUserAvatar;
  /**
   * Handler for the `DELETE /api/user/management` operation.
   */
  deleteUser: typeof handleDeleteUser;
  /**
   * Handler for the `GET /api/user/management` operation.
   */
  listUsers: typeof handleListUsers;
  /**
   * Handler for the `POST /api/user/management` operation.
   */
  createUser: typeof handleCreateUser;
  /**
   * Handler for the `PUT /api/user/management` operation.
   */
  editUser: typeof handleEditUser;
  /**
   * Handler for the `GET /api/user/management/{uuid}` operation.
   */
  userInfo: typeof handleUserInfo;
  /**
   * Handler for the `GET /api/user/management/mail` operation.
   */
  mailActive: typeof handleMailActive;
  /**
   * Handler for the `GET /api/user/management/groups` operation.
   */
  listGroupsSimple: typeof handleListGroupsSimple;
  /**
   * Handler for the `PUT /api/user/management/password` operation.
   */
  resetUserPassword: typeof handleResetUserPassword;
  /**
   * Handler for the `POST /api/user/management/email` operation.
   */
  changeUserEmail: typeof handleChangeUserEmail;
  /**
   * Handler for the `PUT /api/user/management/convert-oidc` operation.
   */
  convertOidcUser: typeof handleConvertOidcUser;
  /**
   * Handler for the `GET /api/settings/general` operation.
   */
  getGeneralSettings: typeof handleGetGeneralSettings;
  /**
   * Handler for the `GET /api/settings/user` operation.
   */
  getUserSettings: typeof handleGetUserSettings;
  /**
   * Handler for the `POST /api/settings/user` operation.
   */
  saveUserSettings: typeof handleSaveUserSettings;
  /**
   * Handler for the `GET /api/settings/mail` operation.
   */
  getMailSettings: typeof handleGetMailSettings;
  /**
   * Handler for the `POST /api/settings/mail` operation.
   */
  saveMailSettings: typeof handleSaveMailSettings;
  /**
   * Handler for the `POST /api/mail/reset/send` operation.
   */
  sendResetLink: typeof handleSendResetLink;
  /**
   * Handler for the `POST /api/mail/reset/confirm` operation.
   */
  resetPassword: typeof handleResetPassword;
  /**
   * Handler for the `POST /api/mail/test` operation.
   */
  testMail: typeof handleTestMail;
  /**
   * Handler for the `DELETE /api/group` operation.
   */
  deleteGroup: typeof handleDeleteGroup;
  /**
   * Handler for the `GET /api/group` operation.
   */
  listGroups: typeof handleListGroups;
  /**
   * Handler for the `POST /api/group` operation.
   */
  createGroup: typeof handleCreateGroup;
  /**
   * Handler for the `PUT /api/group` operation.
   */
  editGroup: typeof handleEditGroup;
  /**
   * Handler for the `GET /api/group/{uuid}` operation.
   */
  groupInfo: typeof handleGroupInfo;
  /**
   * Handler for the `GET /api/group/users` operation.
   */
  listUsersSimple: typeof handleListUsersSimple;
  /**
   * Handler for the `GET /api/dummy/test` operation.
   */
  test: typeof handleTest;
};

export type CreateMswHandlersResult = {
  all: (options?: {
    pick?: {
      [K in keyof MswHandlerFactories]?:
        | Parameters<MswHandlerFactories[K]>[0]
        | Parameters<MswHandlerFactories[K]>;
    };
  }) => ReadonlyArray<HttpHandler>;
  pick: MswHandlerFactories;
};

export function createMswHandlers(
  config: RequestHandlerOptions = {}
): CreateMswHandlersResult {
  type Handler<R> = (
    response?: R,
    options?: RequestHandlerOptions
  ) => HttpHandler;
  function wrap<R>(handler: Handler<R>): Handler<R> {
    return (response, options) => handler(response, { ...config, ...options });
  }
  const pick: CreateMswHandlersResult['pick'] = {
    isSetup: wrap(handleIsSetup),
    completeSetup: wrap(handleCompleteSetup),
    getOidcSettings: wrap(handleGetOidcSettings),
    initOidc: wrap(handleInitOidc),
    key: wrap(handleKey),
    authenticate: wrap(handleAuthenticate),
    logout: wrap(handleLogout),
    testToken: wrap(handleTestToken),
    authConfig: wrap(handleAuthConfig),
    updatePassword: wrap(handleUpdatePassword),
    startEmailChange: wrap(handleStartEmailChange),
    updateAccount: wrap(handleUpdateAccount),
    confirmEmailChange: wrap(handleConfirmEmailChange),
    updateAvatar: wrap(handleUpdateAvatar),
    info: wrap(handleInfo),
    avatarById: wrap(handleAvatarById),
    resetUserAvatar: wrap(handleResetUserAvatar),
    deleteUser: wrap(handleDeleteUser),
    listUsers: wrap(handleListUsers),
    createUser: wrap(handleCreateUser),
    editUser: wrap(handleEditUser),
    userInfo: wrap(handleUserInfo),
    mailActive: wrap(handleMailActive),
    listGroupsSimple: wrap(handleListGroupsSimple),
    resetUserPassword: wrap(handleResetUserPassword),
    changeUserEmail: wrap(handleChangeUserEmail),
    convertOidcUser: wrap(handleConvertOidcUser),
    getGeneralSettings: wrap(handleGetGeneralSettings),
    getUserSettings: wrap(handleGetUserSettings),
    saveUserSettings: wrap(handleSaveUserSettings),
    getMailSettings: wrap(handleGetMailSettings),
    saveMailSettings: wrap(handleSaveMailSettings),
    sendResetLink: wrap(handleSendResetLink),
    resetPassword: wrap(handleResetPassword),
    testMail: wrap(handleTestMail),
    deleteGroup: wrap(handleDeleteGroup),
    listGroups: wrap(handleListGroups),
    createGroup: wrap(handleCreateGroup),
    editGroup: wrap(handleEditGroup),
    groupInfo: wrap(handleGroupInfo),
    listUsersSimple: wrap(handleListUsersSimple),
    test: wrap(handleTest)
  };
  const all: CreateMswHandlersResult['all'] = (options = {}) => {
    type OverrideValue<R> = R | [response?: R, options?: RequestHandlerOptions];
    function invoke<R>(
      fn: Handler<R>,
      override?: OverrideValue<R>
    ): HttpHandler {
      return Array.isArray(override) ? fn(...override) : fn(override);
    }
    const overrides = options.pick ?? {};
    return [
      invoke(pick.avatarById, overrides.avatarById),
      invoke(pick.updatePassword, overrides.updatePassword),
      invoke(pick.startEmailChange, overrides.startEmailChange),
      invoke(pick.updateAccount, overrides.updateAccount),
      invoke(pick.confirmEmailChange, overrides.confirmEmailChange),
      invoke(pick.updateAvatar, overrides.updateAvatar),
      invoke(pick.resetUserAvatar, overrides.resetUserAvatar),
      invoke(pick.mailActive, overrides.mailActive),
      invoke(pick.listGroupsSimple, overrides.listGroupsSimple),
      invoke(pick.resetUserPassword, overrides.resetUserPassword),
      invoke(pick.changeUserEmail, overrides.changeUserEmail),
      invoke(pick.convertOidcUser, overrides.convertOidcUser),
      invoke(pick.sendResetLink, overrides.sendResetLink),
      invoke(pick.resetPassword, overrides.resetPassword),
      invoke(pick.userInfo, overrides.userInfo),
      invoke(pick.getOidcSettings, overrides.getOidcSettings),
      invoke(pick.initOidc, overrides.initOidc),
      invoke(pick.key, overrides.key),
      invoke(pick.authenticate, overrides.authenticate),
      invoke(pick.logout, overrides.logout),
      invoke(pick.testToken, overrides.testToken),
      invoke(pick.authConfig, overrides.authConfig),
      invoke(pick.info, overrides.info),
      invoke(pick.deleteUser, overrides.deleteUser),
      invoke(pick.listUsers, overrides.listUsers),
      invoke(pick.createUser, overrides.createUser),
      invoke(pick.editUser, overrides.editUser),
      invoke(pick.getGeneralSettings, overrides.getGeneralSettings),
      invoke(pick.getUserSettings, overrides.getUserSettings),
      invoke(pick.saveUserSettings, overrides.saveUserSettings),
      invoke(pick.getMailSettings, overrides.getMailSettings),
      invoke(pick.saveMailSettings, overrides.saveMailSettings),
      invoke(pick.testMail, overrides.testMail),
      invoke(pick.listUsersSimple, overrides.listUsersSimple),
      invoke(pick.test, overrides.test),
      invoke(pick.groupInfo, overrides.groupInfo),
      invoke(pick.isSetup, overrides.isSetup),
      invoke(pick.completeSetup, overrides.completeSetup),
      invoke(pick.deleteGroup, overrides.deleteGroup),
      invoke(pick.listGroups, overrides.listGroups),
      invoke(pick.createGroup, overrides.createGroup),
      invoke(pick.editGroup, overrides.editGroup)
    ];
  };
  return { all, pick };
}
