// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  AuthConfigData,
  AuthConfigErrors,
  AuthConfigResponses,
  AuthenticateData,
  AuthenticateErrors,
  CompleteSetupData,
  CompleteSetupErrors,
  CreateGroupData,
  CreateGroupErrors,
  CreateGroupResponses,
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  DeleteGroupData,
  DeleteGroupErrors,
  DeleteGroupResponses,
  DeleteUserData,
  DeleteUserErrors,
  DeleteUserResponses,
  EditGroupData,
  EditGroupErrors,
  EditGroupResponses,
  EditUserData,
  EditUserErrors,
  EditUserResponses,
  GetGeneralSettingsData,
  GetGeneralSettingsErrors,
  GetGeneralSettingsResponses,
  GetMailSettingsData,
  GetMailSettingsErrors,
  GetMailSettingsResponses,
  GetUserSettingsData,
  GetUserSettingsErrors,
  GetUserSettingsResponses,
  GroupInfoData,
  GroupInfoErrors,
  GroupInfoResponses,
  InfoData,
  InfoErrors,
  InfoResponses,
  IsSetupData,
  IsSetupErrors,
  IsSetupResponses,
  KeyData,
  KeyResponses,
  ListGroupsData,
  ListGroupsErrors,
  ListGroupsResponses,
  ListGroupsSimpleData,
  ListGroupsSimpleErrors,
  ListGroupsSimpleResponses,
  ListUsersData,
  ListUsersErrors,
  ListUsersResponses,
  ListUsersSimpleData,
  ListUsersSimpleErrors,
  ListUsersSimpleResponses,
  LogoutData,
  LogoutErrors,
  MailActiveData,
  MailActiveErrors,
  MailActiveResponses,
  ResetPasswordData,
  ResetPasswordErrors,
  ResetPasswordResponses,
  ResetUserAvatarData,
  ResetUserAvatarErrors,
  ResetUserAvatarResponses,
  ResetUserPasswordData,
  ResetUserPasswordErrors,
  ResetUserPasswordResponses,
  SaveMailSettingsData,
  SaveMailSettingsErrors,
  SaveMailSettingsResponses,
  SaveUserSettingsData,
  SaveUserSettingsErrors,
  SaveUserSettingsResponses,
  SendResetLinkData,
  SendResetLinkErrors,
  SendResetLinkResponses,
  TestData,
  TestErrors,
  TestMailData,
  TestMailErrors,
  TestMailResponses,
  TestResponses,
  TestTokenData,
  UpdateAccountData,
  UpdateAccountErrors,
  UpdateAccountResponses,
  UpdateAvatarData,
  UpdateAvatarErrors,
  UpdateAvatarResponses,
  UpdatePasswordData,
  UpdatePasswordErrors,
  UpdatePasswordResponses,
  UserInfoData,
  UserInfoErrors,
  UserInfoResponses
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const isSetup = <ThrowOnError extends boolean = false>(
  options?: Options<IsSetupData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    IsSetupResponses,
    IsSetupErrors,
    ThrowOnError
  >({ url: '/api/setup', ...options });

export const completeSetup = <ThrowOnError extends boolean = false>(
  options: Options<CompleteSetupData, ThrowOnError>
) =>
  (options.client ?? client).post<unknown, CompleteSetupErrors, ThrowOnError>({
    url: '/api/setup',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const key = <ThrowOnError extends boolean = false>(
  options?: Options<KeyData, ThrowOnError>
) =>
  (options?.client ?? client).get<KeyResponses, unknown, ThrowOnError>({
    url: '/api/auth/password',
    ...options
  });

export const authenticate = <ThrowOnError extends boolean = false>(
  options: Options<AuthenticateData, ThrowOnError>
) =>
  (options.client ?? client).post<unknown, AuthenticateErrors, ThrowOnError>({
    url: '/api/auth/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>
) =>
  (options?.client ?? client).post<unknown, LogoutErrors, ThrowOnError>({
    url: '/api/auth/logout',
    ...options
  });

export const testToken = <ThrowOnError extends boolean = false>(
  options?: Options<TestTokenData, ThrowOnError>
) =>
  (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    url: '/api/auth/test_token',
    ...options
  });

export const authConfig = <ThrowOnError extends boolean = false>(
  options?: Options<AuthConfigData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AuthConfigResponses,
    AuthConfigErrors,
    ThrowOnError
  >({ url: '/api/auth/config', ...options });

export const updateAvatar = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAvatarData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UpdateAvatarResponses,
    UpdateAvatarErrors,
    ThrowOnError
  >({
    url: '/api/user/account/avatar',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const updatePassword = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePasswordData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UpdatePasswordResponses,
    UpdatePasswordErrors,
    ThrowOnError
  >({
    url: '/api/user/account/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const updateAccount = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAccountData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UpdateAccountResponses,
    UpdateAccountErrors,
    ThrowOnError
  >({
    url: '/api/user/account/update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const info = <ThrowOnError extends boolean = false>(
  options?: Options<InfoData, ThrowOnError>
) =>
  (options?.client ?? client).get<InfoResponses, InfoErrors, ThrowOnError>({
    url: '/api/user/info',
    ...options
  });

export const deleteUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteUserResponses,
    DeleteUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListUsersResponses,
    ListUsersErrors,
    ThrowOnError
  >({ url: '/api/user/management', ...options });

export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateUserResponses,
    CreateUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editUser = <ThrowOnError extends boolean = false>(
  options: Options<EditUserData, ThrowOnError>
) =>
  (options.client ?? client).put<
    EditUserResponses,
    EditUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const userInfo = <ThrowOnError extends boolean = false>(
  options: Options<UserInfoData, ThrowOnError>
) =>
  (options.client ?? client).get<
    UserInfoResponses,
    UserInfoErrors,
    ThrowOnError
  >({ url: '/api/user/management/{uuid}', ...options });

export const mailActive = <ThrowOnError extends boolean = false>(
  options?: Options<MailActiveData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    MailActiveResponses,
    MailActiveErrors,
    ThrowOnError
  >({ url: '/api/user/management/mail', ...options });

export const listGroupsSimple = <ThrowOnError extends boolean = false>(
  options?: Options<ListGroupsSimpleData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListGroupsSimpleResponses,
    ListGroupsSimpleErrors,
    ThrowOnError
  >({ url: '/api/user/management/groups', ...options });

export const resetUserAvatar = <ThrowOnError extends boolean = false>(
  options: Options<ResetUserAvatarData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    ResetUserAvatarResponses,
    ResetUserAvatarErrors,
    ThrowOnError
  >({
    url: '/api/user/management/avatar',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const resetUserPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetUserPasswordData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ResetUserPasswordResponses,
    ResetUserPasswordErrors,
    ThrowOnError
  >({
    url: '/api/user/management/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const getGeneralSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetGeneralSettingsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetGeneralSettingsResponses,
    GetGeneralSettingsErrors,
    ThrowOnError
  >({ url: '/api/settings/general', ...options });

export const getUserSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserSettingsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetUserSettingsResponses,
    GetUserSettingsErrors,
    ThrowOnError
  >({ url: '/api/settings/user', ...options });

export const saveUserSettings = <ThrowOnError extends boolean = false>(
  options: Options<SaveUserSettingsData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SaveUserSettingsResponses,
    SaveUserSettingsErrors,
    ThrowOnError
  >({
    url: '/api/settings/user',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const getMailSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetMailSettingsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetMailSettingsResponses,
    GetMailSettingsErrors,
    ThrowOnError
  >({ url: '/api/settings/mail', ...options });

export const saveMailSettings = <ThrowOnError extends boolean = false>(
  options: Options<SaveMailSettingsData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SaveMailSettingsResponses,
    SaveMailSettingsErrors,
    ThrowOnError
  >({
    url: '/api/settings/mail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const sendResetLink = <ThrowOnError extends boolean = false>(
  options: Options<SendResetLinkData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SendResetLinkResponses,
    SendResetLinkErrors,
    ThrowOnError
  >({
    url: '/api/mail/reset/send',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const resetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetPasswordData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ResetPasswordResponses,
    ResetPasswordErrors,
    ThrowOnError
  >({
    url: '/api/mail/reset/confirm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const testMail = <ThrowOnError extends boolean = false>(
  options?: Options<TestMailData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    TestMailResponses,
    TestMailErrors,
    ThrowOnError
  >({ url: '/api/mail/test', ...options });

export const deleteGroup = <ThrowOnError extends boolean = false>(
  options: Options<DeleteGroupData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteGroupResponses,
    DeleteGroupErrors,
    ThrowOnError
  >({
    url: '/api/group',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listGroups = <ThrowOnError extends boolean = false>(
  options?: Options<ListGroupsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListGroupsResponses,
    ListGroupsErrors,
    ThrowOnError
  >({ url: '/api/group', ...options });

export const createGroup = <ThrowOnError extends boolean = false>(
  options: Options<CreateGroupData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateGroupResponses,
    CreateGroupErrors,
    ThrowOnError
  >({
    url: '/api/group',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editGroup = <ThrowOnError extends boolean = false>(
  options: Options<EditGroupData, ThrowOnError>
) =>
  (options.client ?? client).put<
    EditGroupResponses,
    EditGroupErrors,
    ThrowOnError
  >({
    url: '/api/group',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const groupInfo = <ThrowOnError extends boolean = false>(
  options: Options<GroupInfoData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GroupInfoResponses,
    GroupInfoErrors,
    ThrowOnError
  >({ url: '/api/group/{uuid}', ...options });

export const listUsersSimple = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersSimpleData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListUsersSimpleResponses,
    ListUsersSimpleErrors,
    ThrowOnError
  >({ url: '/api/group/users', ...options });

export const test = <ThrowOnError extends boolean = false>(
  options?: Options<TestData, ThrowOnError>
) =>
  (options?.client ?? client).get<TestResponses, TestErrors, ThrowOnError>({
    url: '/api/dummy/test',
    ...options
  });
