// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:5173' | (string & {});
};

export type AccountUpdate = {
  username: string;
};

export type AuthConfig = {
  instant_redirect: boolean;
  mail_enabled: boolean;
  sso_type: SsoType;
};

export type AvatarUpdate = {
  avatar: string;
};

export type CreateGroupRequest = {
  name: string;
};

export type CreateUser = {
  email: string;
  name: string;
  password?: string | null;
};

export type CreateUserResponse = {
  uuid: string;
};

export type DeleteGroupRequest = {
  uuid: string;
};

export type DeleteUserRequest = {
  uuid: string;
};

export type DetailUserInfo = {
  avatar?: string | null;
  email: string;
  groups: Array<SimpleGroupInfo>;
  name: string;
  permissions: Array<string>;
  uuid: string;
};

export type EditGroupRequest = {
  name: string;
  permissions: Array<string>;
  users: Array<string>;
  uuid: string;
};

export type GeneralSettings = {
  site_url: string;
};

export type GroupCreateResponse = {
  uuid: string;
};

export type GroupDetails = {
  id: string;
  name: string;
  permissions: Array<string>;
  users: Array<SimpleUserInfo>;
};

export type GroupInfo = {
  id: string;
  name: string;
  permissions: Array<string>;
  users: Array<SimpleUserInfo>;
};

export type GroupViewPath = {
  uuid: string;
};

export type IsSetupResponse = {
  db_backend: string;
  is_setup: boolean;
};

export type KeyRes = {
  key: string;
};

export type ListGroupResponse = {
  admin_group?: string | null;
  groups: Array<GroupInfo>;
};

export type LoginReq = {
  email: string;
  password: string;
};

export type MailActiveResponse = {
  active: boolean;
};

export type MailSettings = {
  smtp?: SmtpSettings | null;
};

export type OidcCallbackQuery = {
  code?: string | null;
  error?: string | null;
  state: string;
};

export type OidcSettings = {
  client_id: string;
  client_secret: string;
  issuer: string;
  scopes: Array<string>;
};

export type PasswordUpdate = {
  new_password: string;
  old_password: string;
};

export type ResetPasswordPayload = {
  new_password: string;
  token: string;
};

export type ResetRequest = {
  email: string;
};

export type ResetUserPassword = {
  new_password: string;
  uuid: string;
};

export const SsoType = { OIDC: 'Oidc', NONE: 'None' } as const;

export type SsoType = (typeof SsoType)[keyof typeof SsoType];

export type SetupPayload = {
  admin_email: string;
  admin_password: string;
  admin_username: string;
};

export type SimpleGroupInfo = {
  name: string;
  uuid: string;
};

export type SimpleUserInfo = {
  id: string;
  name: string;
};

export type SmtpSettings = {
  from_address: string;
  from_name: string;
  password: string;
  port: number;
  server: string;
  use_tls: boolean;
  username: string;
};

export type UserAvatarResetRequest = {
  uuid: string;
};

export type UserEditReq = {
  groups: Array<string>;
  name: string;
  uuid: string;
};

export type UserInfo = {
  avatar?: string | null;
  email: string;
  name: string;
  permissions: Array<string>;
  uuid: string;
};

export type UserListInfo = {
  avatar?: string | null;
  email: string;
  groups: Array<SimpleGroupInfo>;
  name: string;
  uuid: string;
};

export type UserSettings = {
  oidc?: OidcSettings | null;
  sso_create_user: boolean;
  sso_instant_redirect: boolean;
};

export type UserViewPath = {
  uuid: string;
};

export type IsSetupData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/setup';
};

export type IsSetupErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type IsSetupResponses = {
  200: IsSetupResponse;
};

export type IsSetupResponse2 = IsSetupResponses[keyof IsSetupResponses];

export type CompleteSetupData = {
  body: SetupPayload;
  path?: never;
  query?: never;
  url: '/api/setup';
};

export type CompleteSetupErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type CompleteSetupError = CompleteSetupErrors[keyof CompleteSetupErrors];

export type KeyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/password';
};

export type KeyResponses = {
  200: KeyRes;
};

export type KeyResponse = KeyResponses[keyof KeyResponses];

export type AuthenticateData = {
  body: LoginReq;
  path?: never;
  query?: never;
  url: '/api/auth/password';
};

export type AuthenticateErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type AuthenticateError = AuthenticateErrors[keyof AuthenticateErrors];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/logout';
};

export type LogoutErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type TestTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/test_token';
};

export type AuthConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/config';
};

export type AuthConfigErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type AuthConfigResponses = {
  200: AuthConfig;
};

export type AuthConfigResponse = AuthConfigResponses[keyof AuthConfigResponses];

export type UpdateAvatarData = {
  body: AvatarUpdate;
  path?: never;
  query?: never;
  url: '/api/user/account/avatar';
};

export type UpdateAvatarErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type UpdateAvatarError = UpdateAvatarErrors[keyof UpdateAvatarErrors];

export type UpdateAvatarResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type UpdatePasswordData = {
  body: PasswordUpdate;
  path?: never;
  query?: never;
  url: '/api/user/account/password';
};

export type UpdatePasswordErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type UpdatePasswordError =
  UpdatePasswordErrors[keyof UpdatePasswordErrors];

export type UpdatePasswordResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type UpdateAccountData = {
  body: AccountUpdate;
  path?: never;
  query?: never;
  url: '/api/user/account/update';
};

export type UpdateAccountErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type UpdateAccountError = UpdateAccountErrors[keyof UpdateAccountErrors];

export type UpdateAccountResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type InfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/info';
};

export type InfoErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type InfoResponses = {
  200: UserInfo;
};

export type InfoResponse = InfoResponses[keyof InfoResponses];

export type DeleteUserData = {
  body: DeleteUserRequest;
  path?: never;
  query?: never;
  url: '/api/user/management';
};

export type DeleteUserErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ListUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/management';
};

export type ListUsersErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListUsersResponses = {
  200: Array<UserListInfo>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
  body: CreateUser;
  path?: never;
  query?: never;
  url: '/api/user/management';
};

export type CreateUserErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
  200: CreateUserResponse;
};

export type CreateUserResponse2 =
  CreateUserResponses[keyof CreateUserResponses];

export type EditUserData = {
  body: UserEditReq;
  path?: never;
  query?: never;
  url: '/api/user/management';
};

export type EditUserErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type EditUserError = EditUserErrors[keyof EditUserErrors];

export type EditUserResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type UserInfoData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/user/management/{uuid}';
};

export type UserInfoErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type UserInfoResponses = {
  200: DetailUserInfo;
};

export type UserInfoResponse = UserInfoResponses[keyof UserInfoResponses];

export type MailActiveData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/management/mail';
};

export type MailActiveErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type MailActiveResponses = {
  200: MailActiveResponse;
};

export type MailActiveResponse2 =
  MailActiveResponses[keyof MailActiveResponses];

export type ListGroupsSimpleData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user/management/groups';
};

export type ListGroupsSimpleErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListGroupsSimpleResponses = {
  200: Array<SimpleGroupInfo>;
};

export type ListGroupsSimpleResponse =
  ListGroupsSimpleResponses[keyof ListGroupsSimpleResponses];

export type ResetUserAvatarData = {
  body: UserAvatarResetRequest;
  path?: never;
  query?: never;
  url: '/api/user/management/avatar';
};

export type ResetUserAvatarErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ResetUserAvatarError =
  ResetUserAvatarErrors[keyof ResetUserAvatarErrors];

export type ResetUserAvatarResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ResetUserPasswordData = {
  body: ResetUserPassword;
  path?: never;
  query?: never;
  url: '/api/user/management/password';
};

export type ResetUserPasswordErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ResetUserPasswordError =
  ResetUserPasswordErrors[keyof ResetUserPasswordErrors];

export type ResetUserPasswordResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type GetGeneralSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/settings/general';
};

export type GetGeneralSettingsErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type GetGeneralSettingsResponses = {
  200: GeneralSettings;
};

export type GetGeneralSettingsResponse =
  GetGeneralSettingsResponses[keyof GetGeneralSettingsResponses];

export type GetUserSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/settings/user';
};

export type GetUserSettingsErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type GetUserSettingsResponses = {
  200: UserSettings;
};

export type GetUserSettingsResponse =
  GetUserSettingsResponses[keyof GetUserSettingsResponses];

export type SaveUserSettingsData = {
  body: UserSettings;
  path?: never;
  query?: never;
  url: '/api/settings/user';
};

export type SaveUserSettingsErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type SaveUserSettingsError =
  SaveUserSettingsErrors[keyof SaveUserSettingsErrors];

export type SaveUserSettingsResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type GetMailSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/settings/mail';
};

export type GetMailSettingsErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type GetMailSettingsResponses = {
  200: MailSettings;
};

export type GetMailSettingsResponse =
  GetMailSettingsResponses[keyof GetMailSettingsResponses];

export type SaveMailSettingsData = {
  body: MailSettings;
  path?: never;
  query?: never;
  url: '/api/settings/mail';
};

export type SaveMailSettingsErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type SaveMailSettingsError =
  SaveMailSettingsErrors[keyof SaveMailSettingsErrors];

export type SaveMailSettingsResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type SendResetLinkData = {
  body: ResetRequest;
  path?: never;
  query?: never;
  url: '/api/mail/reset/send';
};

export type SendResetLinkErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
};

export type SendResetLinkError = SendResetLinkErrors[keyof SendResetLinkErrors];

export type SendResetLinkResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ResetPasswordData = {
  body: ResetPasswordPayload;
  path?: never;
  query?: never;
  url: '/api/mail/reset/confirm';
};

export type ResetPasswordErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type TestMailData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/mail/test';
};

export type TestMailErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type TestMailResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type DeleteGroupData = {
  body: DeleteGroupRequest;
  path?: never;
  query?: never;
  url: '/api/group';
};

export type DeleteGroupErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type DeleteGroupError = DeleteGroupErrors[keyof DeleteGroupErrors];

export type DeleteGroupResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type ListGroupsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/group';
};

export type ListGroupsErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListGroupsResponses = {
  200: ListGroupResponse;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type CreateGroupData = {
  body: CreateGroupRequest;
  path?: never;
  query?: never;
  url: '/api/group';
};

export type CreateGroupErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type CreateGroupError = CreateGroupErrors[keyof CreateGroupErrors];

export type CreateGroupResponses = {
  200: GroupCreateResponse;
};

export type CreateGroupResponse =
  CreateGroupResponses[keyof CreateGroupResponses];

export type EditGroupData = {
  body: EditGroupRequest;
  path?: never;
  query?: never;
  url: '/api/group';
};

export type EditGroupErrors = {
  /**
   * Failed to parse the request body as JSON
   */
  400: string;
  /**
   * Expected request with `Content-Type: application/json`
   */
  415: string;
  /**
   * Failed to deserialize the JSON body into the target type
   */
  422: string;
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type EditGroupError = EditGroupErrors[keyof EditGroupErrors];

export type EditGroupResponses = {
  /**
   * no content
   */
  200: unknown;
};

export type GroupInfoData = {
  body?: never;
  path: {
    uuid: string;
  };
  query?: never;
  url: '/api/group/{uuid}';
};

export type GroupInfoErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type GroupInfoResponses = {
  200: GroupDetails;
};

export type GroupInfoResponse = GroupInfoResponses[keyof GroupInfoResponses];

export type ListUsersSimpleData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/group/users';
};

export type ListUsersSimpleErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type ListUsersSimpleResponses = {
  200: Array<SimpleUserInfo>;
};

export type ListUsersSimpleResponse =
  ListUsersSimpleResponses[keyof ListUsersSimpleResponses];

export type TestData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/dummy/test';
};

export type TestErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type TestResponses = {
  /**
   * plain text
   */
  200: unknown;
};
